# docker-compose项目目录说明：
#
# project
# |----mysql
# |    |----data
# |----nginx
# |    |----conf.d
# |    |    | bluelog.conf
# |    |----log
# |----bluelog
# |    | ...

version: '3'

services:
    # 定义容器
    mysql:
        # 自定义容器名
        container_name: bluelog-mysql
        image: mysql:8.0
        volumes:
            - ./mysql/data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 111
        ports:
            - "3306:3306"
    bluelog:
        container_name: bluelog-app
        # 基于Dockerfile制作镜像并创建容器
        build:
            context: ./bluelog
        # 链接到mysql容器后数据库连接地址可以写为 mysql:3306
        links:
            - mysql
        # 暴露端口，只允许被链接容器访问
        expose:
            - "8000"
    nginx:
        container_name: bluelog-nginx
        image: nginx:1.19
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
        links:
            - bluelog
        ports:
            - "80:80"
