version: '3'

services:
    # 定义容器
    mysql:
        # 自定义容器名
        container_name: bluelog-mysql
        image: mysql:8
        volumes:
            - /tmp/Bluelog/mysql/data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: qwerdfb
        ports:
            - "3306:3306"
    bluelog:
        container_name: bluelog-app
        # 基于Dockerfile制作镜像并创建容器
        build: .
        volumes:
            - /tmp/Bluelog/uploads:/root/Bluelog/uploads
        environment:
            SQLALCHEMY_DATABASE_URI: mysql+pymysql://root:qwerdfb@mysql:3306/bluelog
        ports:
            - "8000:8000"
        depends_on:
            - mysql
